# values.yaml

server:
  ingress:
    enabled: true
    ingressClassName: nginx 
    hostname: quypx-argocd.poc-h2hubgenai.com 
    annotations:
      kubernetes.io/ingress.class: nginx
      alb.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      