controller:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: quypx-jenkins.poc-h2hubgenai.com
    annotations:
      alb.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  adminPassword: "admin"
persistence:
  enabled: true
  storageClass: gp2
  size: 20Gi
