# [OUTPUT]
#   Name cloudwatch_logs
#   Match   *
#   region ap-southeast-1
#   log_group_name fluent-bit-cloudwatch
#   log_stream_prefix from-fluent-bit-
#   auto_create_group On
## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  ## https://docs.fluentbit.io/manual/pipeline/outputs ####
  outputs: |
    [OUTPUT]
      Name kube_system_logs
      Match kubernetes.* AND kube.namespace == "kube-system"
      region ap-southeast-1
      log_group_name fluent-bit-kube-system
      log_stream_prefix kube-system-
      auto_create_group On

    [OUTPUT]
      Name be_app_logs
      Match kubernetes.* AND kube.namespace == "be-app"
      region ap-southeast-1
      log_group_name fluent-bit-be-app
      log_stream_prefix be-app-
      auto_create_group On
    